apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:extension-{{ .Values.serviceName }}:{{ .Values.serviceName }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - dns.gardener.cloud
  resources:
  - dnsentries
  - dnsentries/status
  - dnsannotations
  - dnsannotations/status
  {{- if .Values.dnsProviderReplication.enabled }}
  - dnsproviders
  - dnsproviders/status
  {{- end }}
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - update
  - create
{{- if .Values.dnsProviderReplication.enabled }}
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extensions.gardener.cloud:extension-{{ .Values.serviceName }}:{{ .Values.serviceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extensions.gardener.cloud:extension-{{ .Values.serviceName }}:{{ .Values.serviceName }}
subjects:
- kind: User
  name: {{ .Values.userName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: extensions.gardener.cloud:extension-{{ .Values.serviceName }}:{{ .Values.serviceName }}
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extensions.gardener.cloud:extension-{{ .Values.serviceName }}:{{ .Values.serviceName }}
  namespace: kube-system
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.userName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extensions.gardener.cloud:extension-{{ .Values.serviceName }}:{{ .Values.serviceName }}
