apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: {{ template "service.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if or .Values.useProjectedTokenMount .Values.podAnnotations }}
      annotations:
        {{- if .Values.useProjectedTokenMount }}
        # TODO(rfranzke): Remove in a future release.
        security.gardener.cloud/trigger: rollout
        {{- end }}
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
      {{- end }}
      labels:
        app: {{ template "service.name" . }}
        release: {{ .Release.Name }}
        gardener.cloud/role: controlplane
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-seed-apiserver: allowed
        networking.gardener.cloud/from-prometheus: allowed
    spec:
      serviceAccountName: {{ template "service.name" . }}
      containers:
        - name: {{ template "service.name" . }}
          image: {{ index .Values.images "dns-controller-manager" }}
          volumeMounts:
          {{- if .Values.useTokenRequestor }}
          - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
            name: kubeconfig
            readOnly: true
          {{- else }}
          - name: source-cluster
            mountPath: "/etc/source-cluster"
            readOnly: true
          {{- end }}
          args:
          {{- if .Values.useTokenRequestor }}
          - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
          {{- else }}
          - --kubeconfig=/etc/source-cluster/kubeconfig
          {{- end }}
          - --kubeconfig.id={{ .Values.shootId }}
          - --kubeconfig.disable-deploy-crds
          - --target=IN-CLUSTER
          - --target-realms={{ .Release.Namespace }}
          - --target.id={{ .Values.seedId }}
          - --target.disable-deploy-crds
          - --target-owner-id={{ .Values.shootId }}-shootdns
          - --controllers=dnssources,dnsentry-source,annotation{{- if .Values.dnsProviderReplication.enabled -}},dnsprovider-replication{{- end }}
          {{- if .Values.dnsProviderReplication.enabled }}
          - --dnsprovider-replication.target-realms={{ .Release.Namespace }},
          {{- end }}
          - --namespace=kube-system
          - --target-namespace={{ .Release.Namespace }}
          - --target-creator-label-name=gardener.cloud/shoot-id
          - --target-creator-label-value={{ .Values.creatorLabelValue }}
          - --target-set-ignore-owners
          - --dns-target-class=gardendns
          - --dns-class={{ .Values.dnsClass }}
          - --lease-name=shoot-dns-service
          - --lease-resource-lock=leases
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      {{- if .Values.useTokenRequestor }}
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: kubeconfig
                path: kubeconfig
              name: generic-token-kubeconfig
              optional: false
          - secret:
              items:
              - key: token
                path: token
              name: {{ .Values.targetClusterSecret }}
              optional: false
      {{- else }}
      - name: source-cluster
        secret:
          secretName: {{ .Values.targetClusterSecret }}
      {{- end }}
