apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-extension-{{ .Values.serviceName }}-logging-config
  namespace: garden
  labels:
    extensions.gardener.cloud/configuration: logging
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                parser
        Match               kubernetes.*shoot-dns-service*shoot-dns-service*
        Key_Name            log
        Parser              shootDnsServiceParser
        Reserve_Data        True

  parsers.conf: |
    [PARSER]
        Name        shootDnsServiceParser
        Format      regex
        Regex       ^time="(?<time>\d{4}-\d{2}-\d{2}T[^"]*)"\s+level=(?<severity>\w+)\smsg="(?<log>.*)"$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S%z
