{{- if .Values.dnsControllerManager.deploy }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: extensions.gardener.cloud.{{ .Values.serviceName }}.dns-controller-manager
  labels:
{{ include "dnsmanLabels" . | indent 4 }}
{{- if or .Values.dnsControllerManager.security.apparmorEnabled .Values.dnsControllerManager.security.seccompEnabled }}
  annotations:
{{- if .Values.dnsControllerManager.security.apparmorEnabled }}
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
{{- end }}
{{- if .Values.dnsControllerManager.security.seccompEnabled }}
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
{{- end }}
{{- end }}
spec:
  allowedCapabilities: []
  defaultAddCapabilities: []
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - secret
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAs
    ranges:
    - min: 65534
      max: 65534
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 65534
      max: 65534
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 65534
      max: 65534
  readOnlyRootFilesystem: true
{{- end }}