{{- if .Values.dnsControllerManager.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dnsmanLabels" . | indent 4 }}
{{- if .Values.dnsControllerManager.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.dnsControllerManager.serviceAccountAnnotations | indent 4 }}
{{- end }}
{{- if ne .Values.gardener.version "" }}
automountServiceAccountToken: false
{{- end }}
{{- end }}