{{- if .Values.dnsControllerManager.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extensions.gardener.cloud:{{ .Values.serviceName }}:dns-controller-manager
  labels:
{{ include "dnsmanLabels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extensions.gardener.cloud:{{ .Values.serviceName }}:dns-controller-manager
subjects:
- kind: ServiceAccount
  name: dns-controller-manager
  namespace: {{ .Release.Namespace }}
{{- end }}