{{- if and .Values.dnsControllerManager.deploy .Values.dnsControllerManager.remoteaccess.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-controller-manager-remoteaccess-ca
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dnsmanLabels" . | indent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.dnsControllerManager.remoteaccess.certs.ca.cert }}
{{- if .Values.dnsControllerManager.remoteaccess.certs.ca.key }}
  ca.key: {{ .Values.dnsControllerManager.remoteaccess.certs.ca.key }}
{{- end }}
{{- if not .Values.dnsControllerManager.remoteaccess.certs.server.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-controller-manager-remoteaccess-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  tls.crt: {{ .Values.dnsControllerManager.remoteaccess.certs.server.cert }}
  tls.key: {{ .Values.dnsControllerManager.remoteaccess.certs.server.key }}
{{- end }}
{{- end }}
