apiVersion: {{ include "priorityclassversion" . }}
kind: PriorityClass
metadata:
  name: gardener-extension-{{ .Values.serviceName }}
value: 1000000000
globalDefault: false
description: "Priority class for the Gardener extension: shoot-dns-service."