---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:{{ .Values.serviceName }}:shoot-services
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups:
    - dns.gardener.cloud
  resources:
    - dnsentries
    - dnsentries/status
  verbs:
    - get
    - list
    - update
    - watch
    - create
    - delete
