apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-{{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
automountServiceAccountToken: false
